wayfinder-project/wayfinder

- .gitignore
- README.md
- client/README.md
- server/README.md
- server/pom.xml
- server/src/main/java/com/wayfinder/server/servlets/TestServlet.java
- server/src/main/webapp/WEB-INF/web.xml
This is so I can test the build triggers.
> Merge dev branch to master

- server/pom.xml
- server/src/main/java/com/wayfinder/server/servlets/TestServlet.java
- server/src/main/java/com/wayfinder/server/util/Passwords.java
- server/src/main/resources/log4j2.properties
I added a utility class (copied from my project 1, which was copied from my project 0) for hashing/salting passwords. This is also a good time to test if Jenkins will check PRs.
> Add utility class for password hashing and salting

- client/src/app/app.module.ts
- client/src/app/components/login/login.component.html
- client/src/app/components/login/login.component.spec.ts
- client/src/app/components/login/login.component.ts
> initial login component

- server/src/main/java/com/wayfinder/server/beans/Route.java
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/resources/beans.xml
ACTUALLY adding data to user beans.
> Adding data to User Bean

- README.md
- server/src/main/resources/beans.xml
This PR changes the Spring config to take database credentials from environment variables.
> Recognize environment variables in Spring config

- server/src/main/java/com/wayfinder/server/beans/Leg.java
- server/src/main/java/com/wayfinder/server/beans/Route.java
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/java/com/wayfinder/server/beans/Waypoint.java
- server/src/main/java/com/wayfinder/server/repository/LegRepository.java
- server/src/main/java/com/wayfinder/server/repository/RouteRepository.java
- server/src/main/java/com/wayfinder/server/repository/UserRepository.java
- server/src/main/java/com/wayfinder/server/repository/WaypointRepository.java
- server/src/main/java/com/wayfinder/server/services/UserService.java
This PR adds beans for all route components (Route, Leg, Waypoint) and corresponding repositories.
> Add trip beans

- client/src/app/components/map/map.component.ts
> adhering to tslint

- README.md
- server/pom.xml
- server/src/main/java/com/wayfinder/server/beans/Leg.java
- server/src/main/java/com/wayfinder/server/beans/ResponseError.java
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/java/com/wayfinder/server/beans/UserWithPassword.java
- server/src/main/java/com/wayfinder/server/controllers/ErrorController.java
- server/src/main/java/com/wayfinder/server/controllers/UserController.java
- server/src/main/java/com/wayfinder/server/exceptions/UserAlreadyExistsException.java
- server/src/main/java/com/wayfinder/server/exceptions/UserNotFoundException.java
- server/src/main/java/com/wayfinder/server/services/UserService.java
- server/src/main/webapp/WEB-INF/beans.xml
- server/src/main/webapp/WEB-INF/web.xml
The documentation is certainly only preliminary, but this should be enough to at least play around with adding/updating/finding users. It also adds Spring MVC to the project, which is nice.
> Set up Spring MVC and add user controller

- client/src/app/app.component.html
- client/src/app/app.module.ts
> Trying to fix httpclientmodule

- client/package-lock.json
- client/package.json
- client/src/app/components/login/login.component.ts
- client/src/app/models/api-error.model.ts
- client/src/app/models/leg.model.ts
- client/src/app/models/route.model.ts
- client/src/app/models/user.model.ts
- client/src/app/models/waypoint.model.ts
- client/src/app/services/auth/auth.service.ts
- client/src/app/services/user/user.service.spec.ts
- client/src/app/services/user/user.service.ts
- client/src/app/utils/types.ts
- client/src/environments/environment.prod.ts
- client/src/environments/environment.ts
- server/src/main/java/com/wayfinder/server/controllers/UserController.java
All back-end API endpoints now have a corresponding method in UserService.
> Add user service to front-end

- client/src/app/components/login/login.component.css
- client/src/app/components/login/login.component.html
Using the absolute path (`/assets/<whatever>`) seems to work fine.
> Update asset paths to work with deployed version

- client/src/app/app.component.html
- client/src/app/components/login/login.component.html
- client/src/app/components/login/login.component.ts
- client/src/app/services/auth/auth.service.ts
- client/src/app/utils/error.interceptor.ts
- client/src/app/utils/token.storage.ts
- server/pom.xml
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/java/com/wayfinder/server/beans/UserCredentials.java
- server/src/main/java/com/wayfinder/server/controllers/ErrorController.java
- server/src/main/java/com/wayfinder/server/controllers/LoginController.java
- server/src/main/java/com/wayfinder/server/controllers/UserController.java
- server/src/main/java/com/wayfinder/server/security/JwtTokenFilter.java
- server/src/main/java/com/wayfinder/server/security/JwtTokenProvider.java
- server/src/main/java/com/wayfinder/server/security/SecurityWebApplicationInitializer.java
- server/src/main/java/com/wayfinder/server/security/WebSecurityConfig.java
This completes support for JWTs on the server and client side; login and token authentication are confirmed to be working.
> Complete JWT support

- README.md
- server/src/main/java/com/wayfinder/server/beans/Leg.java
- server/src/main/java/com/wayfinder/server/beans/Route.java
- server/src/main/java/com/wayfinder/server/beans/Trip.java
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/java/com/wayfinder/server/beans/Waypoint.java
- server/src/main/java/com/wayfinder/server/controllers/LoginController.java
- server/src/main/java/com/wayfinder/server/security/JwtTokenFilter.java
- server/src/main/java/com/wayfinder/server/security/JwtTokenProvider.java
- server/src/main/java/com/wayfinder/server/security/SecurityWebApplicationInitializer.java
- server/src/main/java/com/wayfinder/server/security/WebSecurityConfig.java
Some minor code cleanup, and also refactoring the JWT secret into an environment variable.
> Clean up code

- README.md
- client/src/app/components/userpage/userpage.component.ts
- client/src/app/services/user/user.service.ts
- server/src/main/java/com/wayfinder/server/beans/PasswordChangeRequest.java
- server/src/main/java/com/wayfinder/server/controllers/UserController.java
- server/src/main/java/com/wayfinder/server/services/UserService.java
This includes both the back-end and front-end components.
> Add ability to change a user's password

- client/src/app/app-routing/app-routing.module.ts
- client/src/app/app.component.html
- client/src/app/app.module.ts
- client/src/app/components/home/home.component.html
- client/src/app/components/login/login.component.html
- client/src/app/components/login/login.component.ts
- client/src/app/components/navbar/navbar.component.css
- client/src/app/components/navbar/navbar.component.html
- client/src/app/components/navbar/navbar.component.ts
- client/src/app/guards/access.guard.ts
- client/src/app/guards/auth.guard.ts
- server/src/main/java/com/wayfinder/server/controllers/ErrorController.java
- server/src/main/java/com/wayfinder/server/security/WebSecurityConfig.java
- server/src/main/java/com/wayfinder/server/services/UserService.java
This PR integrates all the front-end components using routing, and also completes the login, create user and update user/password functionality (design will still have to be improved, though).
> Integrate front-end components and complete login/new user/update user

- README.md
- client/src/app/app.module.ts
- client/src/app/models/annotated-waypoint.model.ts
- client/src/app/models/trip.model.ts
- server/src/main/java/com/wayfinder/server/beans/AnnotatedWaypoint.java
- server/src/main/java/com/wayfinder/server/beans/Trip.java
This will allow the user to specify places they're interested in (e.g. hotels, sights, etc.) and save them for later use.
> Add annotated waypoints to Trip model

- client/src/app/app.component.html
- client/src/app/components/map/map.component.html
- client/src/app/components/map/map.component.ts
Updating the filter on location to include radius, as well as updating place markers to agm-markers and returning place details when clicked.
> Location filter update

- .gitignore
- server/pom.xml
- server/src/main/java/com/wayfinder/server/aspects/ControllerLoggingAspect.java
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/webapp/WEB-INF/beans.xml
- server/src/test/java/com/wayfinder/server/config/ControllerTestConfig.java
- server/src/test/java/com/wayfinder/server/controllers/UserControllerTest.java
Currently, only the UserController is tested, but I plan to test more of the application down the line.
> Add logging and tests to back-end code

- server/src/main/java/com/wayfinder/server/controllers/UserController.java
- server/src/test/java/com/wayfinder/server/controllers/UserControllerTest.java
> Restrict endpoint access

- client/src/app/components/userpage/userpage.component.ts
- client/src/app/models/user.model.ts
- client/src/app/services/user/user.service.ts
This PR fixes a userpage compilation error by refining the types used in the UserService (in particular, being specific about when an ID is required).
> Fix client bugs by refining UserService method types

- server/src/main/java/com/wayfinder/server/beans/AnnotatedWaypoint.java
- server/src/main/java/com/wayfinder/server/beans/Checklist.java
- server/src/main/java/com/wayfinder/server/beans/ChecklistItem.java
- server/src/main/java/com/wayfinder/server/beans/PasswordChangeRequest.java
- server/src/main/java/com/wayfinder/server/beans/ResponseError.java
- server/src/main/java/com/wayfinder/server/beans/Route.java
- server/src/main/java/com/wayfinder/server/beans/Trip.java
- server/src/main/java/com/wayfinder/server/beans/User.java
- server/src/main/java/com/wayfinder/server/beans/UserCredentials.java
- server/src/main/java/com/wayfinder/server/beans/UserWithPassword.java
- server/src/main/java/com/wayfinder/server/beans/Waypoint.java
Basically just removing useless annotations and adding hashCode, equals and toString to POJOs.
> Clean up server

- client/src/app/app.module.ts
- client/src/app/components/checklist-modal/checklist-modal.component.html
- client/src/app/components/checklist-modal/checklist-modal.component.spec.ts
- client/src/app/components/checklist-modal/checklist-modal.component.ts
- client/src/environments/environment.ts
It currently is not present in any component, but it's functional.
> Add trip checklist component

- client/src/app/components/map/map.component.ts
- client/src/app/models/marker.model.ts
- server/src/main/java/com/wayfinder/server/beans/AnnotatedWaypoint.java
- server/src/main/java/com/wayfinder/server/beans/ResponseError.java
- server/src/main/java/com/wayfinder/server/beans/Trip.java
- server/src/main/java/com/wayfinder/server/beans/Waypoint.java
- server/src/main/java/com/wayfinder/server/controllers/ErrorController.java
- server/src/main/webapp/WEB-INF/beans.xml
There were a few minor bugs in the trip saving functionality, which are now fixed.
> Fixed trip saving functionality

- client/src/app/app.component.html
The app component was changed again...
> Fix app component

- client/src/app/components/map/map.component.html
- client/src/app/components/map/map.component.ts
- client/src/app/directives/places-autocomplete.directive.ts
- client/src/environments/environment.ts
Fixing how the waypoints are saved.
> Address update

- README.md
- client/CNAME
- client/package-lock.json
- client/package.json
- client/src/environments/environment.prod.ts
Deployment is back onto GitHub pages! And the production API is now accessed through https://api.wayfinder-project.com.
> Update deployment configuration

- client/src/app/components/annotate-marker-modal/annotate-marker-modal.component.html
- client/src/app/components/annotate-marker-modal/annotate-marker-modal.component.ts
- client/src/app/components/edit-trip/edit-trip.component.ts
- client/src/app/components/map/map.component.html
- client/src/app/components/map/map.component.ts
- client/src/app/models/marker.model.ts
Saving now populates all data successfully (except the waypoint numbers).
> Adding updated data to waypoints from loading

- client/src/app/components/map/map.component.html
Fixing the wrong calls on the address fields
> Fixing the route display from address

- client/src/app/components/map/map.component.html
- client/src/app/components/map/map.component.ts
- client/src/app/models/marker.model.ts
Added reverse geocoding on button presses and added deleting saved markers.
> Quick fixes

- client/src/app/components/map/map.component.ts
The waypoints are now correctly numbered by their position in the route.
> Fix waypoint marker numbering

- README.md
- client/src/app/components/create-trip/create-trip.component.ts
- client/src/app/components/map/map.component.html
- client/src/app/components/trip-list/trip-list.component.html
- client/src/app/models/trip.model.ts
- server/src/main/java/com/wayfinder/server/beans/Trip.java
Users can now name their trips, and the titles will be displayed in the list of trips.
> Add titles to trips

- client/src/app/components/map/map.component.html
- client/src/app/components/map/map.component.ts
- client/src/app/models/place.model.ts
Added websites to place details.
> Quick fixes 3

- server/src/main/java/com/wayfinder/server/beans/AnnotatedWaypoint.java
- server/src/main/java/com/wayfinder/server/beans/User.java
> Fix note duplication bug
